language: node_js
node_js:
  - '0.12'
script: grunt ci
before_install:
  - npm install -g grunt-cli
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start #X Virtual Framebuffer
  - sleep 5 #Give time for xvfb to start